### ISSUE TITLE
`bake clean && bake sodium` fails because of parallel compiling

### ISSUE THREAD

**Issue by SJFrK** [SJFrK/redox-baker#1]
The problem lies with the parallel compiling of the dependencies. If I change cake's `par!` to serial processing, everything works.

@ticki Am I using cake wrong or is this a bug? Cake should wait on the completion of dependencies before starting the next one up the tree. And I think it tried to compile libcore twice (in parallel) because it's the dependency of multiple libraries.

**Comment by ticki** [comment]
Oh, :/ that's right, there's a bug. Will fix it.

**Comment by ticki** [comment]
It is fixed!
